### ISSUE TITLE
TypeScript support?

### ISSUE THREAD

**Issue by endigo** [messagebird/messagebird-nodejs#14]

**Comment by izolate** [comment]
Hey @endigo - thanks for this good suggestion! At the moment it's not currently on the roadmap, as other work is taking priority (updates to include all our API endpoints for example). But this is definitely something to consider for the future.

In the meantime, PRs are welcome. We'd be thrilled to review one 👍

**Comment by MatejBalantic** [comment]
+1 for the TypeScript support

**Comment by niekert** [comment]
Typings were added in #27 and published in `v2.3.2`  🎉
