### ISSUE TITLE
MMS support

### ISSUE THREAD

**Issue by LukasRos** [messagebird/messagebird-nodejs#19]
MMS support is missing from the SDK.

**Comment by epels** [comment]
Hi @LukasRos, thanks for opening an issue! We're aware of the absence of MMS support. Adding it is definitely on the roadmap, but not planned yet.

**Comment by epels** [comment]
@LukasRos Hi Lukas, this issue has been resolved in https://github.com/messagebird/messagebird-nodejs/releases/tag/2.3.0 with thanks to @canuzunoglu and reviewers. Enjoy!
