### ISSUE TITLE
Refactor httpRequest

### ISSUE THREAD

**Issue by epels** [messagebird/messagebird-nodejs#21]
```javascript
function httpRequest(method, path, params, callback)
```

`httpRequest` is not very flexible: it does, for example, assume all request bodies should be JSON encoded. There's an endpoint where this should not be the case (`PUT /groups/{groupId}/contacts`).

It'd be nice to refactor this method and allow for more flexibility. [As suggested](https://github.com/messagebird/messagebird-nodejs/pull/20#discussion_r219502262) by @izolate (thanks!) it could be implemented as follows:

```javascript
var CONTENT_TYPE_FORM_URLENCODED = 'application/x-www-form-urlencoded';

read: function (id, callback) {
  httpRequest({
    method: 'GET',
    path: '/endpoint' + id,
    callback: callback,
    headers: {
      /*
       * Define some default headers in the httpRequest method,
       * then allow them to be overwritten. We could also avoid the 
       * JSON encode unless the content type is set to 'application/json'
       */
      'Content-Type': CONTENT_TYPE_FORM_URLENCODED
    },
  });
},
```

**Comment by niekert** [comment]
Was done by @odrzutowiec in https://github.com/messagebird/messagebird-nodejs/pull/26 🎉
