### ISSUE TITLE
Typings and/or Typescript implementation

### ISSUE THREAD

**Issue by julien-c** [messagebird/messagebird-nodejs#37]
would be awesome :)

Let me know if it's on the roadmap

**Comment by marcelcorso** [comment]
Hey @julien-c! Miste @elmarburke did good work here https://github.com/messagebird/messagebird-nodejs/pull/27. 
Is this what you are talking about?

**Comment by julien-c** [comment]
Yes! Looks like I missed this. Feel free to either close, or to keep open for a potential Typescript reimplementation.
