### ISSUE TITLE
Vulnerability of set-value dependency

### ISSUE THREAD

**Issue by Ebioro** [messagebird/messagebird-nodejs#40]
Hi guys,

While using your sdk I've got this message. Is this something you can fix or I should be concerned about?

![image](https://user-images.githubusercontent.com/40391152/63165152-dcf95d00-c02a-11e9-9a18-a9b133202140.png)

**Comment by alexismoreau** [comment]
see #38

**Comment by niekert** [comment]
Hi, thanks for the report and apologies for the delay. We've just published a new version that fixes the dependency vulnerability: https://github.com/messagebird/messagebird-nodejs/releases/tag/v3.0.0
