### ISSUE TITLE
[BUG] Error TS2307: Cannot find module 'feature'.

### ISSUE THREAD

**Issue by lucasferreiralsf** [messagebird/messagebird-nodejs#42]
Hello, i found an error when using messagebird with nestjs and typescript. When I run the code, it throw the error:
**"node_modules/messagebird/types/index.d.ts(24,26): error TS2307: Cannot find module 'feature'."**

Can you help me?

**Comment by chandel-abhishek** [comment]
facing same issue

**Comment by niekert** [comment]
Hello, this was supposedly resolved in version 3.0.1 https://github.com/messagebird/messagebird-nodejs/releases/tag/v3.0.1

please let us know if you still face problems.
