### ISSUE TITLE
Export Default?

### ISSUE THREAD

**Issue by tstachl** [messagebird/messagebird-nodejs#55]
https://github.com/messagebird/messagebird-nodejs/blob/633bb8c021685f5beaec1960e8fe65bb63c39e5c/types/index.d.ts#L366

Can you guys fix your Typescript types to not use `export default`, it doesn't work and I'm getting the following type error:

`TypeError: messagebird_1.default is not a function`

Here is also some additional reading on why `export default` is bad: 
* [Why we have banned default exports in Javascript and you should do the same](https://blog.neufund.org/why-we-have-banned-default-exports-and-you-should-do-the-same-d51fdc2cf2ad)
* [Default Is Bad](https://github.com/basarat/typescript-book/blob/master/docs/tips/defaultIsBad.md)

**Comment by aodinok** [comment]
Hey @tstachl, can you please check now, I've added example how to use it with TypeScript and fixed the typings. Please let me know if still doesn't work for you.

**Comment by tstachl** [comment]
Hey @aodinok, it works with `esModuleInterop`, thanks for the tip. I decided to dynamically load `messagebird` now like so:

```ts
import("messagebird").then((messagebird: any) => {
  const client = messagebird("API_KEY");
  return new Promise((resolve, reject) => {
    client.balance.read((err, data) => {
      if (err) reject(err);
      resolve(data);
    });
  });
});
```

**Comment by bahador-r** [comment]
same issue

**Comment by etiennea** [comment]
Using esModuleInterop is not an ideal solution

**Comment by VersusF** [comment]
Hello, any update on this? `esModuleInterop` is not compatible with other libraries that we use. Currently the only solution is:
```typescript
// eslint-disable-next-line @typescript-eslint/no-var-requires
this.messageBirdClient = require("messagebird")("MESSAGEBIRD_KEY");
```
But it is not the best one
