### ISSUE TITLE
How do you merge contacts in conversations

### ISSUE THREAD

**Issue by cdedreuille** [messagebird/messagebird-nodejs#61]
It is my understanding that the conversation API is made to show a unified discussion for every contact but for now every time someone is contacting us it result in different contacts for every channels. Is there a way to merge channels for a single contact using the API or directly in Inbox?

**Comment by tiago-123** [comment]
I also think this is a must for messagebird. Hope they implement a way of merging contacts.

**Comment by aodinok** [comment]
Hey guys, right now we do not have a way to merge multiple contacts from API that is exposed publically.
We have this feature available in ContactsV2 but it is only used internally so we can't add this to this library.
This is something that might be exposed in the future though.
