### ISSUE TITLE
messagebird.verify.create always returning undefined

### ISSUE THREAD

**Issue by blindibrasil** [messagebird/messagebird-nodejs#66]
How do I return the object from the following operation since it only returns undefined.
```
const resp = await this.messagebird.verify.create(
      to,
      params,
      (err: any, response: any) => {
        if (err) {
          return console.log(err);
        }
        console.log(response);
        return response;
      },
    );
```
The console.log inside the function returns correctly, but **const resp** always returns undefined.

**Comment by kozmoz** [comment]
The await syntax only works inside async functions.

So you have to wrap the entire code inside a new async function, or rewrite it as Promise.

**Comment by aodinok** [comment]
Hi @blindibrasil 

As @kozmoz  suggested you will need to wrap method in Promise if you want to use async/await syntax, because the library is designed to work with callbacks.

Try something like this:

`
function verifyCreate() {
  return new Promise((resolve, reject) => {
     this.messagebird.verify.create(
        to,
        params,
        (err: any, response: any) => {
          if (err) {
            reject(err);
          } else {
            resolve(response)
          }
        },
      );
  })
}`
