### ISSUE TITLE
Messages delete is not implemented

### ISSUE THREAD

**Issue by Kalliser** [messagebird/messagebird-nodejs#70]
It in your API documentation but not implemented in nodejs API this is probably the part missing:

` delete: function (id, callback) {
        httpRequest({ method: 'DELETE', path: '/messages/' + id}, callback);
      },
`
Or you should expose the httpRequest function so we can fullfill missing implementation by ourselves.

**Comment by aodinok** [comment]
Hey, @Kalliser 
I've added them.
Will try to get it merged next week:
https://github.com/messagebird/messagebird-nodejs/pull/71

**Comment by aodinok** [comment]
Merged and released/published v3.6.0 with this
