### ISSUE TITLE
React Native (Expo) error message on app launch

### ISSUE THREAD

**Issue by asalha** [messagebird/messagebird-nodejs#80]
I run:
expo start -c

And I get the following message:

![InkedWindowsTerminal_Zi9wbGZ7Ug_LI](https://user-images.githubusercontent.com/4199314/119977946-dde45000-bf6d-11eb-86ba-4b704aa9b03d.jpg)

Response code: 500

![Inkedqemu-system-x86_64_gwKSqQIJHD_LI](https://user-images.githubusercontent.com/4199314/119979195-73ccaa80-bf6f-11eb-8589-e7e99d57946e.jpg)

**Comment by aodinok** [comment]
Hey @asalha 

messagebird-**nodejs** package is not fully compatible with React Native as it's name suggests

It is using 'https', 'querystring' modules that are automatically provided by nodejs. These modules are available in Node, but they are not automatically available in other environments such as browsers and in this case React Native.

There are some ways to kind of "polyfil" those modules and include core node modules in React Native. You can check something like ReactNativify to do it.
